### ISSUE TITLE
Create /about

### ISSUE THREAD

**Issue by tonycurises** [gulabs/gubridge-nft-ui#16]
- create /about to know the app version 
- /about is the EB health check path

**Comment by tonycurises** [comment]
@cuonghx1108 
I notice that it does not appear yet. Please take a look.
https://dev.nft-bridge.gu.net/about

**Comment by cuonghx-dev** [comment]
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/100658449/209250682-83f1b7bc-c6b4-45e1-9986-309f90825452.png">
 Here @tonycurises

**Comment by tonycurises** [comment]
Got it. Thanks.
